### ISSUE TITLE
Incorrect text sent to "Translate all"

### ISSUE THREAD

**Issue by wilejczuk** [easably/extension#25]
**Describe the bug**
Previous sentence sent to Google translate, relatively to the selected word.

**To Reproduce**
1. Go to https://github.com/taqtile-us/manifest-web/wiki/Notes
2. Select the word highlighted in red (_render_ - see the screenshot).
3. Choose "Translate all" in context menu.
4. See error (sentence highlighted is green translates).

**Expected behavior**
Sentence that includes the selected word should be sent to Google translate.

**Screenshots**
<img width="1923" alt="Screenshot (33)" src="https://user-images.githubusercontent.com/50916363/58811637-d6ad3480-8628-11e9-8a90-296a9e423129.png">

**Desktop (please replace with your actual data):**
 - OS: [Win 10]
 - Browser [Google Chrome]
 - Version [74.0.3729.169]

**Comment by pavladan** [comment]
578fd73
