### ISSUE TITLE
[Extension] Widget redesign

### ISSUE THREAD

**Issue by NadiaZu** [easably/extension#34]
- [x] It is required to remove page reload when turning on and off the extension
- [x] Extension window redesign
https://www.figma.com/file/ZUxUOUyMaRSoKlsExXGXlT/EasyLang-new?node-id=158%3A216

**Comment by pavladan** [comment]
49008431dca0c17bc54e27695ff3622651dce780, af985417a52e37564b528a78383ca7b947a7a3d5, 994a88fa2df0d5a10531de64fb3f42d85d0c0e4d, 7476e4670ee71eaeafe002c0795391a28ebae4e5, 745d7815a61d21e2ac6433f3b9df7ce455ececee, cb4602983bcab428874ab2035214f91fd449733d
