### ISSUE TITLE
[Extension] When hiding a word, dots are not displayed correctly.

### ISSUE THREAD

**Issue by NadiaZu** [easably/extension#39]
**Describe the bug**
Add a word to the dictionary. There is an opportunity to hide a word in a text article. Hide the word. Points are not centered horizontally.

**Expected behavior**
Points should be centered on the line.

**Screenshots**
![image](https://user-images.githubusercontent.com/55742055/71086052-eac21900-21a9-11ea-93a2-56215122a4a5.png)

**Desktop (please replace with your actual data):**
 - OS: [Win 10]
 - Browser [Google Chrome]
 - Version [74.0.3729.169]

**Comment by sini4ka08** [comment]
Bug is fixed. It doesn't repeat.
