### ISSUE TITLE
v 2019.12.24 List issues 

### ISSUE THREAD

**Issue by sergeifedorenko** [easably/extension#44]
**Bug list**
- [ ] installation error (see pic 1)
- [x] I did sign-in but didn't get info about it, but the login was successful!
- [x] I not sure, maybe we need the text correction (see pic 2)

**Screenshots**
1 
![image](https://user-images.githubusercontent.com/5947223/71469986-d9958f80-27db-11ea-86df-5781767f8933.png)

2
![image](https://user-images.githubusercontent.com/5947223/71469990-e0240700-27db-11ea-8320-d98fac519d76.png)

**Desktop (please replace with your actual data):**
 - OS: [MAC]
 - Browser Google Chrome v 79.0.3945.88

**Comment by lizakostyushkina** [comment]
![image](https://user-images.githubusercontent.com/58728395/71471233-ed42f500-27df-11ea-87ae-d37d1c06e6bc.png)

Can't Sign up and login

**Comment by pavladan** [comment]
> ![image](https://user-images.githubusercontent.com/58728395/71471233-ed42f500-27df-11ea-87ae-d37d1c06e6bc.png)
> 
> Can't Sign up nor login
> 
> 1. The button doesn't work
> 2. Error messages don't correspond real situation
> 
> Windows 10
> Chrome v 79.0.3945.88

Fixed in https://github.com/easably/extension/releases/tag/0.8.46
