### ISSUE TITLE
[Extension] Main page redesign

### ISSUE THREAD

**Issue by lizakostyushkina** [easably/extension#56]
We create less emphasis on Tutor

**Comment by lizakostyushkina** [comment]
https://www.figma.com/file/ZUxUOUyMaRSoKlsExXGXlT/EasyLang%2Fnew?node-id=158%3A216
![image](https://user-images.githubusercontent.com/58728395/73639962-71f61e00-467e-11ea-80fd-e8dd8d085bd9.png)

**Comment by pavladan** [comment]
https://github.com/easably/extension/releases/tag/0.8.53

**Comment by lizakostyushkina** [comment]
@pavladan  
Please adjust spaces between text [Figma](https://www.figma.com/file/ZUxUOUyMaRSoKlsExXGXlT/EasyLang-new?node-id=795%3A791)
![image](https://user-images.githubusercontent.com/58728395/73726416-91557f80-4740-11ea-82d0-689493ec01df.png)

**Comment by pavladan** [comment]
> @pavladan
> Please adjust spaces between text [Figma](https://www.figma.com/file/ZUxUOUyMaRSoKlsExXGXlT/EasyLang-new?node-id=795%3A791)
> ![image](https://user-images.githubusercontent.com/58728395/73726416-91557f80-4740-11ea-82d0-689493ec01df.png)

Fixed on this release: [Release](https://github.com/easably/extension/releases/tag/0.8.54)
