### ISSUE TITLE
[Extension] Non-logged in user after QR scanning doesn't auto log in to mobile

### ISSUE THREAD

**Issue by sini4ka08** [easably/extension#57]
If the user didn't log in to the mobile, after QR scanning on the desktop doesn't auto log in to the mobile.
QR code
![QR code](https://user-images.githubusercontent.com/52330389/74719197-a5bb7100-5244-11ea-85aa-262973bb867c.png)
URL in the mobile - https://2mymemory.com/login?qr=5c60b9ae6966b286

Additional info:  
If the user is logged in on a mobile phone, after a QR scan on the desktop, the system automatically logs on to the mobile phone.

**Comment by ErgerSusha** [comment]
Fixed in [this](https://github.com/easably/context-tutor/commit/418aa770acf60d98d72607986ba04047cbe48c01) commit in context-tutor.
