### ISSUE TITLE
[Extension] The user can't verify his email address in his mail.

### ISSUE THREAD

**Issue by sini4ka08** [easably/extension#58]
**Describe the bug**
The user received an email with verification of his email address after registration.  An active link opens a page 

URL - https://2mymemory.com/api/auth/register/confirmEmail/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTkzLCJpYXQiOjE1ODIwMTczNjYsImV4cCI6MTU4MjYyMjE2Nn0.IYWPPjTWFAf8u-2baciI3lc7jjp5EovpneogcQ-vWL8 

with code - 
{ "statusCode": 404, "error" : "not Found", "message": "Can not GET /api/auth/register/confirmEmail/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTkzLCJpYXQiOjE1ODIwMTczNjYsImV4cCI6MTU4MjYyMjE2Nn0.IYWPPjTWFAf8u-2baciI3lc7jjp5EovpneogcQ-vWL8"}

**Expected behavior**
The active link must verify the email address in the user's email.

**Desktop:**

- OS: [Windows 8]
- Browser [Google Chrome]
- Version [80.0.3987.106]

**Comment by ErgerSusha** [comment]
FIxed on both environments at backend side.

**Comment by sini4ka08** [comment]
**Describe the bug**
User can verify his email address. But an active button [Close this page] 
![verify email address](https://user-images.githubusercontent.com/52330389/74820052-665b5600-5312-11ea-9852-400eb2a51bae.png)
leads to the registration page.
![verify email address2](https://user-images.githubusercontent.com/52330389/74820075-6fe4be00-5312-11ea-9b9a-26a07c79c493.png)

**Expected behavior**
User can verify his email address. And user clicks on the button [Close this page] and gets to their account in easy4learn.com.

**Desktop:**

- OS: [Windows 8]
- Browser [Google Chrome]
- Version [80.0.3987.106]

**Comment by ErgerSusha** [comment]
Fixed latest issue of [development](https://2mymemory.com) environment on backend side.

**Comment by sini4ka08** [comment]
Bug is fixed.
