### ISSUE TITLE
[UX] UI Suggestions

### ISSUE THREAD

**Issue by sergeifedorenko** [easably/extension#61]
![image](https://user-images.githubusercontent.com/5947223/75217622-95594800-57a8-11ea-9eb3-b4249802cd55.png)

![image](https://user-images.githubusercontent.com/5947223/75217780-1b758e80-57a9-11ea-8a8d-53fe9a387dbe.png)

The last picture for comparison

![image](https://user-images.githubusercontent.com/5947223/75217795-24666000-57a9-11ea-9724-fb8534364051.png)

**Comment by lizakostyushkina** [comment]
[Extension changes  ](https://www.figma.com/file/ZUxUOUyMaRSoKlsExXGXlT/EasyLang%2Fnew?node-id=1018%3A940)
@pavladan

**Comment by pavladan** [comment]
Fixed in 6614ff7c864328e1d3611d0f2bcc1511850a2a9b commit
