### ISSUE TITLE
[Extension] Suggestions that improve the usability of working with a extension

### ISSUE THREAD

**Issue by sini4ka08** [easably/extension#66]
**Is your feature request related to a problem? Please describe.**
- [ ] History takes up a lot of space in the extension menu.
History (1) field takes up too much space in the extension menu. And the main points (2) are practically not noticeable.
**Screenshot**
![History is too much](https://user-images.githubusercontent.com/52330389/75958904-385b4180-5ece-11ea-9d8d-a212424fe922.png)

- [ ] You can place [Sign out] & [Privacy Policy] on the main page from the settings. It will be more logical.
**Screenshot**
![History is too much2](https://user-images.githubusercontent.com/52330389/75958784-fc27e100-5ecd-11ea-8a4b-58198844bc9b.png)

**Comment by annamaksimik** [comment]
**Updated the history window**
![image](https://user-images.githubusercontent.com/58423687/76063109-1cbc6d80-5f98-11ea-93bc-a3ab305597cc.png)

### **Extension is the main thing
Tutor-additional application**
![image](https://user-images.githubusercontent.com/58423687/76064172-2e9f1000-5f9a-11ea-880a-8604a4015d25.png)

it is not logical to place the login and privacy policy on the main page

**Comment by sini4ka08** [comment]
Ok.
